### ISSUE TITLE
GlutenOut

### ISSUE THREAD

**Issue by Daramary** [glutenfreemap/glutenfreemap.github.io#16]
### Name

GlutenOut 

### Category(ies)

Bakery

### Address

Mercado Municipal do Seixal 
Seixal 

### Description

Fabrico de pão sem gluten e biologico 
Certificado pela APC
Bolos de aniversário e salgados

**Comment by aaubry** [comment]
Obrigado pela sugestão! Vamos validar a informação e adicionar o estabelecimento.

**Comment by aaubry** [comment]
Contactámos o estabelecimento para obter mais algumas informações com o fim de incluí-lo na aplicação. Estamos a aguardar uma resposta do mesmo.

**Comment by aaubry** [comment]
O Gluten'Out foi adicionado à aplicação. Obrigado pela sugestão!
